### ISSUE TITLE
Cobalt Strike integration

### ISSUE THREAD

**Issue by sohelahmed786** [snovvcrash/DInjector#5]
Hi team,

I'm getting this error: 
![image](https://user-images.githubusercontent.com/12643717/169640943-d2a8f324-bf87-4e26-8cc3-6de25921e1a4.png)

It is trying to find DInjector.exe but after building the project I get DInjector.dll file. How do i get DInjector.exe file?

**Comment by Ming-XF** [comment]
i can't compile  for vs.
no DInvoke module
i try download DInvoke but it show this
"Win32.WinBase no exists SECURITY_ATIRIBUTES"
can you help me?

**Comment by sohelahmed786** [comment]
> i can't compile  for vs.
> 
> no DInvoke module
> 
> i try download DInvoke but it show this
> 
> "Win32.WinBase no exists SECURITY_ATIRIBUTES"
> 
> can you help me?

clone it using github desktop. then complie with VS.

**Comment by Ming-XF** [comment]
so how did you deal with it

**Comment by sohelahmed786** [comment]
> so how did you deal with it
> 
> 

I cloned it using github desktop. You get this option in the web page.

**Comment by Ming-XF** [comment]
Thinks
